config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users do
    resources :occassions
  end
  put '/occassions/:id/increment', to: 'occassions#increment', as: 'increment'
  # only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/occassion.rb
class Occassion < ApplicationRecord
  belongs_to :user
  validates :occassion, presence: true
  attribute :drink_num, :integer, default: 0

  def time_remaining
    passed_time = Time.now - created_at
    remaining_time = ((drink_num * 5400) - passed_time)
    Time.at(remaining_time, in: 0)
    # .strftime("%H:%M:%S")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :occassions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/occassions_controller.rb
class OccassionsController < ApplicationController
  before_action :set_user

  def index
    if User.find(@user.id) || User.find(params[:user_id])
    @occassions = Occassion.where("user_id = ?", @user.id)
    else
      redirect_to root
    end
  end

  def show
    @occassion = Occassion.find(params[:id])
  end

  def new
    @occassion = Occassion.new
  end

  def create
    @occassion = Occassion.new(occassion_params)
    @occassion.user = @user
    @occassion.save!
    redirect_to user_occassion_path(@user, @occassion)
  end

  def edit
    @occassion = Occassion.find(params[:id])
  end

  def update
    @occassion = Occassion.find(params[:id])
    @occassion.update(occassion_params)
    redirect_to occassion_path(@occassion)
  end

  def increment
    @occassion = Occassion.find(params[:id])
    @occassion.increment!(:drink_num)
    redirect_to user_occassion_path(@user, @occassion)
  end

  def destroy
    @occassion = Occassion.find(params[:id])
    @occassion.destroy
    redirect_to user_occassions_path(@user)
  end

  private

  def occassion_params
    params.require(:occassion).permit(:occassion)
  end

  def set_user
    @user = current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  before_action :set_user

  def home
  end

  private

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drinkapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
      <%= render 'shared/flashes' %>
      <div class="footer">
      </div>
    </div>
  </body>
</html>

app/views/occassions/edit.html.erb
<%= simple_form_for @occassion do |f| %>
  <%= f.input :occassion %>
  <%= f.input :drink_num %>
  <%= f.button :submit %>
<% end %>

app/views/occassions/index.html.erb
<div class="occ-grid">
  <div class="occ">
    <h1 class="occ-title">
      List of all the occassions
    </h1>
<ul>
  <% @occassions.sort.each do |item| %>
    <div class="bar-container">
    <%= link_to(user_occassion_path(@user, item), class: "bar-link") do %>
      <li class="bar">
        <h3><%= item.occassion %></h3>
        <div class="bar-grid">
          <p>🍸 <%= item.drink_num %></p>
          <p>🗓 <%= item.created_at.strftime("%d-%m-%y") %></p>
        </div>
      </li>
    <%= link_to "Delete", user_occassion_path(@user, item), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"  %>
    <% end %>
    </div>
  <% end %>
</ul>
<h2>Add an occassion</h2>
<%= button_to "Add an occassion", new_user_occassion_path, method: :get, class: "btn btn-success" %>
</div>

app/views/occassions/new.html.erb
<%= simple_form_for [ @user, @occassion ] do |f| %>
  <%= f.input :occassion %>
  <%= f.button :submit %>
<% end %>

app/views/occassions/show.html.erb
<div class="occ-grid">
  <div class="occ">
    <h1 class="occ-title">
      🎉 Occassion 🎉
    </h1>
    <h3 class="occ-input">
      <%= @occassion.occassion %>
    </h3>
  </div>
  <div class="drinks">
    <p class="occ-input">Number of drinks:</p>
    <div class="drink_num"><%= @occassion.drink_num %></div>
  </div>
  <div class="drinks">
  <p class="occ-input">Add a drink</p>
  <%= link_to(increment_path(@occassion), method: :put, class: "increment") do %>
  <i class="fas fa-plus"></i>
  <% end %>
  </div>
  <div class="drinks">
  <h3 class="time-title">
    Remaining time
  </h3>
  <div class="time-box">
    <i class="fas fa-clock time-icon"></i>
    <% if @occassion.drink_num > 0 %>
    <table id="clockdiv">
      <tr>
        <td class="days"></td>
        <td class="hours"></td>
        <td class="minutes"></td>
        <td class="seconds"></td>
      </tr>
    </table>
    <% else  %>
    <p>No drinks yet</p>
    <% end %>
  </div>
  </div>
<%= link_to "Return to home", user_occassions_path, class: "btn btn-info" %>
</div>

  <script type="text/javascript">
    function getTimeRemaining(endtime) {
      const passed_time = Date.parse(new Date()) - Date.parse(endtime);
      const total = Math.floor((<%= @occassion.drink_num %> * 5400000) - passed_time);
      const seconds = Math.floor((total / 1000) % 60);
      const minutes = Math.floor((total / 1000 / 60) % 60);
      const hours = Math.floor((total / (1000 * 60 * 60)) % 24);
      const days = Math.floor(total / (1000 * 60 * 60 * 24));

      return {
        total,
        days,
        hours,
        minutes,
        seconds
      };
    }

    function initializeClock(id, endtime) {
      const clock = document.getElementById(id);
      const daysSpan = clock.querySelector('.days');
      const hoursSpan = clock.querySelector('.hours');
      const minutesSpan = clock.querySelector('.minutes');
      const secondsSpan = clock.querySelector('.seconds');

      function updateClock() {
        const t = getTimeRemaining(endtime);
        daysSpan.innerHTML = t.days + 'D';
        hoursSpan.innerHTML = ('0' + t.hours).slice(-2) + 'H';
        minutesSpan.innerHTML = ('0' + t.minutes).slice(-2) + 'M';
        secondsSpan.innerHTML = ('0' + t.seconds).slice(-2) + 'S';

        if (t.total <= 0) {
          clearInterval(timeinterval);
        }
      }

      const timeinterval = setInterval(updateClock, 1000);
      updateClock();
    }

    var deadline = '<%= @occassion.created_at %>'.replace(/\-/g, "/");
    initializeClock('clockdiv', deadline);
  </script>

app/views/pages/home.html.erb
<div class="occ-grid">
  <div class="occ">
    <h1 class="occ-title">
      DrinkApp
    </h1>
<div class="drinks">
  <% if !user_signed_in? %>
<%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
<br>
<%= link_to "Sign-up", new_user_registration_path, class: "btn btn-secondary" %>
<% else %>
<%= link_to "Add an occassions", new_user_occassion_path(@user), class: "btn btn-success" %>
<br>
<%= link_to "Check all occassions", user_occassions_path(@user), class: "btn btn-secondary" %>
<% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://www.roads2ranking.com/wp-content/uploads/2018/02/roads2ranking-solo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
      <% else %>
      <% end %>
    </ul>
  </div>
</div>